### ISSUE TITLE
Retroactive Apache 2.0 license approval for 2.2.28

### ISSUE THREAD

**Issue by Dave-Allured** [Unidata/UDUNITS-2#105]
In [issue #102](https://github.com/Unidata/UDUNITS-2/issues/102#issuecomment-758179692) you indicated approval of OSI-approved Apache License 2.0 for upcoming UDUNITS-2 releases.  Would it also be possible to have your retroactive approval of the same license for current release 2.2.28?

I have to ask because distribution of a prebuilt UDUNITS-2 package (binary) is currently blocked on Macports because of [their interpretation of license policy](https://github.com/macports/macports-ports/pull/10347#issuecomment-805879348).

A simple affirmative comment on this Github issue will be sufficient.  Thank you for your consideration.

**Comment by semmerson** [comment]
That's OK with me but I don't see it's possible because version 2.2.28 uses a different license explicitly.

**Comment by Dave-Allured** [comment]
Thank you.  I am not a lawyer.  But I think the way that this works, is if you say something like "it's okay with me for a third party to redistribute a binary version of UDUNITS-2 under the Apache 2.0 License", then you have made a statement on record.  That record then applies to the third party's action.  Another way of looking at it is that the statement replaces the explicit license in 2.2.28, for the specific purpose.

**Comment by semmerson** [comment]
IANAL either, but here goes:

The Apache 2.0 License may be applied to version 2.2.28 of the UDUNITS package at the receiving party's discretion.

Steven Emmerson
UDUNITS Developer

**Comment by Dave-Allured** [comment]
Fantastic.  Thank you.
