### ISSUE TITLE
Support for permil, parts per thousand or parts per kilo unit?

### ISSUE THREAD

**Issue by japhir** [Unidata/UDUNITS-2#111]
* I'm using udunits 2.2.28-3
* From an up-to-date Arch Linux install, using R 4.2.2 and the R package units 0.8

In my field a few different unitless values are used to describe e.g., oxygen and carbon isotope ratios measured on carbonates. We measure them in δ notation, see for example [this wikipedia entry](https://en.wikipedia.org/wiki/%CE%9418O).

The values we report are in parts per thousand, or ‰, typically with uncertainties in the ppm. I saw (in the output of [`valid_udunits()`](https://r-quantities.github.io/units/reference/valid_udunits.html)) that %, ppm, and ppb are part of UDUNITS-2, but didn't see ‰ included. Is there any reason to omit this from inclusion? perhaps ppk could be a good abbreviation, with k for kilo so as not to be ambiguous with ppt = parts per trillion.

Then there's the more complicated (non-SI?) standardisation scheme with Vienna Pee Dee Belemnite (VPDB) and Vienna Standard Mean Ocean Water (VSMOW), and their internal relationships etc. but this may be outside of the scope of UDUNITS-2.

This might be related to the discussions on including unitless salinity https://github.com/Unidata/UDUNITS-2/issues/27

**Comment by semmerson** [comment]
The following unit will be after the unit "percent" in the file "udunits2-common.xml" in the next release:
```
        <unit>
            <comment>Constant</comment>
            <def>0.001</def>
            <aliases>
                <name><singular>permille</singular><noplural/></name>
                <name><singular>per_thousand</singular><noplural/></name>
                <symbol>&#xB0;</symbol>             
                <symbol>ppt</symbol>
            </aliases>
            <definition>number of parts per thousand</definition>
        </unit>
```

Feel free to add it to your, installed "udunits2-common.xml". Be advised, however, that it will not be universally available.

**Comment by japhir** [comment]
Thanks you for its inclusion! :)
