### ISSUE TITLE
Reinstate the "bit" unit

### ISSUE THREAD

**Issue by semmerson** [Unidata/UDUNITS-2#2]
The unit "bit" was dropped in going from UDUNITS-1 to UDUNITS-2. Put it back if it doesn't cause problems.

**Comment by akrherz** [comment]
Hello,  Google landed me here, what was "bit" replaced with?  I am using udunits2-2.1.24 with [netcdf-decoders ruc2 cdl](https://github.com/Unidata/netCDF-Decoders/blob/master/src/gribtonc/cdl/ruc2_236.cdl#L476)

and get the error:
```
Sep  8 18:58:22 metfs1 gribtonc[7335]: /data/netcdf/GRIB/2015090818_ruc2_236.nc: can't get units attribute for variable crain
Sep  8 18:58:22 metfs1 gribtonc[7335]: Error parsing units: bit
```

**Comment by semmerson** [comment]
One can always use "1".
