### ISSUE TITLE
Build requires autotools

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [Unidata/UDUNITS-2#29]
It would be nice if the udunits source has a configure script ready to go. Not all systems have autotools properly installed.

For instance, Apple doesn't deliver autotools with the compilers for OS-X.

It's common practice for source distributions to have autotools already run, so you can just do:

./configure && make && make install

**Comment by semmerson** [comment]
You should be able to just run the configure(1) script and then execute the command `make install`. What happened when you did this?

**Comment by ChrisBarker-NOAA** [comment]
There is no configure script in the repo -- just configure.ac, etc.

That was my suggestion -- that there be a configure script committed to the repo, even though it's generally a "bad idea" to put generated code in source control. 

Or have an official source tarball somewhere that has the configure script generated -- which maybe you do, but I couldn't find it.

**Comment by semmerson** [comment]
I differentiate between a source-code repository and a tarball. The later has a `configure(1)` script; the former doesn't. I'm unlikely to change my policy on this. Sorry.

**Comment by semmerson** [comment]
The official tarball can be found [here](ftp://ftp.unidata.ucar.edu/pub/udunits/). The official website is [here](http://www.unidata.ucar.edu/software/udunits/).

**Comment by ChrisBarker-NOAA** [comment]
So the "official tarball on an ftp site" approach is the way to go. But it turns out that we were pulling from github because that ftp site doesn't maintian older builds:

https://github.com/SciTools/conda-recipes-scitools/issues/17

If you want to have the tarball be the way to get teh source code, you really need to keep older buids around -- at least for a little while.

**Comment by semmerson** [comment]
The FTP repository keeps the last bug-fixed version (the 3rd component of the version ID) of each new-feature release (the 2nd component of the version ID). I don't want people to download a version that has bugs.

**Comment by ChrisBarker-NOAA** [comment]
Makes sense, though it's pretty common practice -- folks need to be smart enough to pull the latest version if that's what they want. And sometimes a bug is _someone's_ feature -- or in any case, they want to be absolutely sure what version they are building against.

The trick here is that we're building a system that auto-builds a bunch of stuff, and have to give it a url to the tarball to download -- when a given file disappears, then it breaks. But maybe that's a good thing -- if it really has known bugs, it probably should break.

So we should come up with a way to do something_or_other.2.2.* that will get the latest.

I have seen sites that have a soft link to the latest, labeled latest, that may be helpful.

**Comment by semmerson** [comment]
I like the idea of a "latest" link. I'll add implementing that to my list. Can't say when I'll get around to it, though -- I'm the only developer on multiple projects.

**Comment by ChrisBarker-NOAA** [comment]
fair enough -- thanks!
