### ISSUE TITLE
Is there a "canonical" source for udunits-2?

### ISSUE THREAD

**Issue by ocefpaf** [Unidata/UDUNITS-2#32]
Hi udunits-2 devs!

In the unidata [webpage](http://www.unidata.ucar.edu/software/udunits/) we have links for releases `2.2.18` `2.1.24`, `2.0.4`, and even `1.12.10`.  And in the GitHub release [page](https://github.com/Unidata/UDUNITS-2/releases) we have from `2.2.0` to `2.2.17`, but no `2.2.18`.  That is a little confusing.  It would be nice to have at least one place with all the releases, legacy and latest alike.

Also, `2.2.18` release seems to be missing `tsearch.c`, which is crucial for windows builds.  See https://github.com/ioos/conda-recipes/pull/143.

Was this intentional?  Is there a chance to get a `2.2.18` GitHub release with the full source that we can compile on Windows?

**Comment by rsignell-usgs** [comment]
And then there is the ftp site:
ftp://ftp.unidata.ucar.edu/pub/udunits/
![4-2-2015 9-42-49 am](https://cloud.githubusercontent.com/assets/1872600/6965069/b7ae5df6-d91c-11e4-8bc5-5b5f0018f667.png)
@semmerson , what's up with this wackiness?!

**Comment by semmerson** [comment]
My bad. I didn't create a 2.2.8 release when I pushed it to GitHub.

It's there now.

There's a difference between a GitHub release and a source-code distribution. The former has all files necessary for developing a package while the latter has only those files necessary for building and installing a package. The site ftp://ftp.unidata.ucar.edu/pub/udunits contains only the most recent "bug fix" versions of all the "minor release" source-code distributions. The GitHub site necessarily contains all versions.

**Comment by semmerson** [comment]
UDUNITS 2.2.19 is now available. It should have the `tsearch` module.

**Comment by semmerson** [comment]
@ocefpaf Regarding the "Hi udunits-2 devs", just so you know, there's only about 0.01 of an FTE working on the UDUNITS package (compared to 2.5 for the netCDF package) -- so things can take a while.

**Comment by ocefpaf** [comment]
> @ocefpaf Regarding the "Hi udunits-2 devs", just so you know, there's only about 0.01 of an FTE working on the UDUNITS package (compared to 2.5 for the netCDF package) -- so things can take a while.


If only I knew C...

Thanks for the answer, release and UDUNITS-2 :grinning: BTW
