### ISSUE TITLE
Incorrect symbol of the astronomical unit

### ISSUE THREAD

**Issue by pascaloettli** [Unidata/UDUNITS-2#36]
Currently, `udunits2` (version 2.2) uses "ua" as symbol for the astronomical unit, and 1 ua is equal to 149,598,000,000 m

    $ udunits2 -H ua -W m
        1 ua = 1.49598e+11 m
        x/m = 1.49598e+11*(x/ua)
   
    $ udunits2 -H au -W m
    udunits2: Units are not convertible

However, according to this [resolution](http://syrte.obspm.fr/IAU_resolutions/Res_IAU2012_B2.pdf) of the XXVIIIe General Assembly of International Astronomy Union (2012), the symbol should now be "au" and 1 au should be equal to 149,597,870,700 m exactly.

**Comment by semmerson** [comment]
The definition for "astronomical unit" that UDUNITS-2 uses came from the US National Institute of Standards and Technology (NIST). See <http://physics.nist.gov/Pubs/SP811/appenB9.html#LENGTH>. It's possible they got both the abbreviation and value wrong.

I'll investigate.

**Comment by semmerson** [comment]
I modified the value of the unit "astronomical_unit" and added the symbol "au". I also added the new unit "astronomical_unit_BIPM_2006" (with symbol "ua") for the old value.

These changes will be in the next release, which might take a while as I'm swamped and the UDUNITS continuous-delivery pipeline is currently broken.
