### ISSUE TITLE
install.sh missing

### ISSUE THREAD

**Issue by edzer** [Unidata/UDUNITS-2#44]
When I try to compile, using
```
autoconf
./configure
```
I see:
```
edzer@gin-edzer:/tmp/UDUNITS-2$ autoconf 
edzer@gin-edzer:/tmp/UDUNITS-2$ ./configure
configure: error: cannot find install-sh, install.sh, or shtool in build-aux "."/build-aux
```
What did I overlook?

**Comment by semmerson** [comment]
Are you trying to install from the tarball or from the repository?

**Comment by edzer** [comment]
From the repo.

On 23 September 2016 16:23:49 CEST, Steven Emmerson <notifications@github.com> wrote:
>Are you trying to install from the tarball or from the repository?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Unidata/UDUNITS-2/issues/44#issuecomment-249206713

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by semmerson** [comment]
Execute the command `autoreconf -fi` and then execute the `configure(1)` script.

**Comment by edzer** [comment]
Thanks, that solved it. Was this somewhere documented? I remember asking this question before, but couldn't find the answer. @Robinlovelace, this also solves your problem.

**Comment by Robinlovelace** [comment]
Many thanks - will test and let you know if I have any issues. Thanks for the software and support!

**Comment by semmerson** [comment]
@edzer It's not really documented. The assumption is that if you're cloning the repository rather than installing from the tarball, then you know what you're doing and don't need that kind of documentation.

**Comment by edzer** [comment]
Fair point, but pretty strong assumption about your users.

**Comment by semmerson** [comment]
@edzer Really? Even though GitHub is for developers and cloning the repository only makes sense for development?

**Comment by edzer** [comment]
A lot of young people think that installing from source and installing from github is the same thing. Your github page does not make the distinction clear for the case of udunits - a one-liner to the github readme: "if you want to install from source, go to this web site" would do. I'm not young, did decades of C programming, wrote configure.in scripts, but never ran into the need for `autoreconf -fi` so far.

Udunits is such a good product. I'm surprised it that there are no binary distributions for platforms like ubuntu 14.04 or 16.04 64 bits - like there are for netcdf.

**Comment by semmerson** [comment]
@edger Yeah. We don't have a good mechanism/tool to generate all the different binary package formats.
