### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by rhardih** [Unidata/UDUNITS-2#57]
Since the traditional LICENSE file has been changed to COPYRIGHT in 2.2.0, Github doesn't provide the easy overview as usual. Furthermore I can't seem to find any wording on "licensing" in general on the support site, which leaves me unsure of the exact terms.

By the look of it, it seems to most resemble the [BSD 4-clause license](https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_(original_%22BSD_License%22)), albeit with slight alterations.

According to https://tldrlegal.com/license/4-clause-bsd, besides copyright and license inclusion in any derivative work, there's also an attribution clause. Is that likewise the case for UDUNITS-2?

Also, is usage of UDUNITS-2 allowed for use in commercial software as well? Given the above provisions are met of course.

**Comment by semmerson** [comment]
The license is more like the BSD 3-clause license with an additional anti-software-patent clause.

There's no mandatory attribution clause.

The package may be used in commercial software as long as the licensing conditions are met.
