### ISSUE TITLE
Representing measurement conditions

### ISSUE THREAD

**Issue by duncanwp** [Unidata/UDUNITS-2#61]
When considering many atmospheric measurements it is important to know if it was made in 'ambient conditions' or 'standard temperature and pressure' conditions.

I've seen many ways these might be represented in the units of a measurement, for example: 'per std cc' or 'cm-3 at stp'. This information is included in a few CF standard names (e.g. 'number_concentration_of_aerosol_particles_at_stp_in_air'), but it's more general than that.

It would be great to be able to represent this consistently in the units, even if it's just in the form of a flag to indicate if the measurement represents ambient conditions or not.

**Comment by semmerson** [comment]
I'm afraid the proper place in which to qualify a physical quantity is not in its unit but, rather, in the physical quantity itself. See section 7.4 of [https://www.nist.gov/pml/nist-guide-si-chapter-7-rules-and-style-conventions-expressing-values-quantities](https://www.nist.gov/pml/nist-guide-si-chapter-7-rules-and-style-conventions-expressing-values-quantities). Modifying the UDUNITS package to accommodate this would complicate it enormously and (as the reference indicates) not adhere to best practice.
