### ISSUE TITLE
nit: whitespace clean

### ISSUE THREAD

**Issue by schwehr** [Unidata/UDUNITS-2#72]
This one is not super important, but it would be nice if the code formatting could be standardized.  My ideal would be to pick a clang-format setup and enforce it.  But baring that, it would be helpful if the code was at least trailing whitespace clean.  e.g.

```bash
find . -type f | xargs perl -pi -e 's/\s+\n/\n/g'
```

**Comment by semmerson** [comment]
You're right: it's a nit.

I did it anyway.

Are you aware that JPL -- the institution responsible for deep space missions like Voyager, Mars Pathfinder, Opportunity, Curiosity, Cassini, Juno, etc. -- doesn't enforce any formatting standard for C code?

**Comment by semmerson** [comment]
@schwehr Noted.
