### ISSUE TITLE
Tag newer versions in git

### ISSUE THREAD

**Issue by chrstphrchvz** [Unidata/UDUNITS-2#94]
The last tagged release is 2.2.27.6. Could git tags for versions 2.2.27.7 - 2.2.27.14 please be created, assuming those are for stable releases?

**Comment by Dave-Allured** [comment]
I asked the developer about this.

>> ... What is your official policy for so-called stable releases?  Only what is
>> on the Unidata FTP site,
>
> Correct.
>
>> or may Github releases be considered official and stable?
>
> Definitely not.

So for external purposes, you have two choices.  Either swipe an unofficial github development version and take a risk, or go with most recent stable, and glean patches as needed for recent bug fixes.  One hopes there will be an official release some time soon.

**Comment by Dave-Allured** [comment]
@chrstphrchvz, there is a new stable release available: 2.2.28.
https://www.unidata.ucar.edu/downloads/udunits/

If you are satisfied with this new release and my advice to only use stable releases, then please close this ticket.  Thank you.
